# This file goes into src/main/resources

server:
  port: 8080
  error:
    include-message: "always"

graphite:
  upload-path: "uploads"

spring:
  servlet:
    multipart:
      max-file-size: 250MB
      max-request-size: 500MB
  main:
    web-application-type: servlet
  data:
    mongodb:
      host: localhost
      port: 27017
      database: graphite
      username: admin
      password: password

# Swagger API docs
springdoc:
  swagger-ui:
    path: "index" # /index

logging:
  file:
    name: graphite.log