server:
  port: 8080
  error:
    include-message: "always"

spring:
  main:
    web-application-type: servlet
  data:
    mongodb:
      host: localhost
      port: 27017
      database: yzyfiles
      username: admin
      password: password

# Swagger API docs
springdoc:
  swagger-ui:
    path: "index" # /index

logging:
  file:
    name: yzyfiles-api.log